vars:
  dependabot_directory: /
  dependabot_ecosystem: auto
  dependabot_interval: weekly
  dependabot_labels: [dependency]

files:
  - repo: afterburn
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [dependency, skip-notes]
      dependabot_interval: monthly

  - repo: airlock
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [kind/dependency]
      dependabot_interval: monthly

  - repo: bootupd
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [area/dependencies]

  - repo: butane
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [dependency, skip-notes]

  - repo: cap-std-ext
    path: .github/dependabot.yml

  # coreos-assembler has some extra rules that aren't yet supported by the
  # template

  - repo: coreos-installer
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [dependency, skip-notes]

  - repo: envsubst-rs
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [dependency, skip-notes]
      dependabot_interval: monthly

  - repo: fedora-coreos-stream-generator
    path: .github/dependabot.yml
    vars:
      dependabot_labels: []
      dependabot_interval: daily

  - repo: go-semver
    path: .github/dependabot.yml

  - repo: go-systemd
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [area/dependencies]

  - repo: ign-converter
    path: .github/dependabot.yml

  - repo: ignition
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [dependency, skip-notes]

  - repo: ignition-config-rs
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [dependency, skip-notes]

  - repo: liboverdrop-rs
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [dependency, skip-notes]
      dependabot_interval: monthly

  - repo: openat-ext
    path: .github/dependabot.yml
    vars:
      dependabot_interval: daily

  - repo: openssh-keys
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [dependency, skip-notes]
      dependabot_interval: monthly

  - repo: repo-templates
    path: .github/dependabot.yml
    vars:
      dependabot_directory: /tmpl8
      dependabot_ecosystem: cargo
      dependabot_interval: monthly

  # rpm-ostree has some extra rules that aren't yet supported by the
  # template

  - repo: stream-metadata-go
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [dependency, skip-notes]

  - repo: stream-metadata-rust
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [dependency, skip-notes]
      dependabot_interval: monthly

  - repo: vcontext
    path: .github/dependabot.yml

  - repo: vmw_backdoor-rs
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [dependency, skip-notes]
      dependabot_interval: monthly

  - repo: zincati
    path: .github/dependabot.yml
    vars:
      dependabot_labels: [area/dependencies]
      dependabot_interval: monthly
