vars:
  branches: [main]

files:
  - repo: butane
    path: .gemini/config.yaml

  - repo: ignition
    path: .gemini/config.yaml

  - repo: coreos-installer
    path: .gemini/config.yaml

  - repo: afterburn
    path: .gemini/config.yaml

  - repo: zincati
    path: .gemini/config.yaml

  - repo: bootupd
    path: .gemini/config.yaml

  - repo: coreos-assembler
    path: .gemini/config.yaml

  - repo: rpm-ostree
    path: .gemini/config.yaml
